name: Publish package to the GitHub Packages
on:
    workflow_dispatch:
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Java
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v2
            - name: Publish package
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
